# Generated by Django 6.0.3 on 2026-03-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_profile_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="home_address",
            field=models.TextField(blank=True, default="No address provided"),
        ),
    ]
