# Generated by Django 6.0.2 on 2026-03-10 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('wishlists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='wishlists', to='books.book'),
        ),
    ]
